// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu58ZnlEHxWPqSj93zNLxkBEikXD6MfRU',
    appId: '1:624305839837:web:869a215af8f3b44bf1c534',
    messagingSenderId: '624305839837',
    projectId: 'creditsea-ec6e4',
    authDomain: 'creditsea-ec6e4.firebaseapp.com',
    storageBucket: 'creditsea-ec6e4.firebasestorage.app',
    measurementId: 'G-4WNY80L1RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgNas7sIaGN69lPmpd4UB0fzmDGcTeD4',
    appId: '1:624305839837:android:cef0bf1ac855c3d7f1c534',
    messagingSenderId: '624305839837',
    projectId: 'creditsea-ec6e4',
    storageBucket: 'creditsea-ec6e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1IPjqN2Ch_cSglnQ22O5fAo_RDu2-3U',
    appId: '1:624305839837:ios:fb89b60e77a02acaf1c534',
    messagingSenderId: '624305839837',
    projectId: 'creditsea-ec6e4',
    storageBucket: 'creditsea-ec6e4.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1IPjqN2Ch_cSglnQ22O5fAo_RDu2-3U',
    appId: '1:624305839837:ios:fb89b60e77a02acaf1c534',
    messagingSenderId: '624305839837',
    projectId: 'creditsea-ec6e4',
    storageBucket: 'creditsea-ec6e4.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu58ZnlEHxWPqSj93zNLxkBEikXD6MfRU',
    appId: '1:624305839837:web:d303bab98d2a7e26f1c534',
    messagingSenderId: '624305839837',
    projectId: 'creditsea-ec6e4',
    authDomain: 'creditsea-ec6e4.firebaseapp.com',
    storageBucket: 'creditsea-ec6e4.firebasestorage.app',
    measurementId: 'G-YKQ9L7LVQS',
  );
}
